apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ${KIBANA_NAME}
  namespace: ${ELASTIC_STACK_NAMESPACE}
spec:
  version: ${ELASTIC_STACK_VERSION}
  count: 1
  elasticsearchRef:
    name: ${ELASTICSEARCH_NAME}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 1Gi
