apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ${KIBANA_NAME}
  namespace: ${ELASTIC_STACK_NAMESPACE}
spec:
  version: ${ELASTIC_STACK_VERSION}
  count: 1
  elasticsearchRef:
    name: ${ELASTICSEARCH_NAME}
  config:
    server.publicBaseUrl: ${KIBANA_PUBLIC_BASE_URL}
    xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTED_SAVED_OBJECTS_KEY}
    xpack.security.encryptionKey: ${KIBANA_SECURITY_ENCRYPTION_KEY}
    xpack.reporting.encryptionKey: ${KIBANA_REPORTING_ENCRYPTION_KEY}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=512"
        - name: KIBANA_ENCRYPTED_SAVED_OBJECTS_KEY
          valueFrom:
            secretKeyRef:
              name: ${KIBANA_ENCRYPTION_SECRET_NAME}
              key: encryptedSavedObjectsKey
        - name: KIBANA_SECURITY_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: ${KIBANA_ENCRYPTION_SECRET_NAME}
              key: securityKey
        - name: KIBANA_REPORTING_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: ${KIBANA_ENCRYPTION_SECRET_NAME}
              key: reportingKey
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            memory: 768Mi
