include ../Makefile.env
include common.mk
include pack-cli.mk
include kp-cli.mk
include helm-cli.mk
include kubectl-cli.mk

.PHONY: install-all-cli

install-all-cli: install-pack-cli install-kp-cli install-helm-cli install-kubectl-cli
