fullnameOverride: keycloak

auth:
  adminUser: admin
  existingSecret: ""
  passwordSecretKey: ""

production: true
tls:
  enabled: false

httpEnabled: true
proxyHeaders: xforwarded
hostnameStrict: false
httpRelativePath: /

replicaCount: 1

ingress:
  enabled: false

service:
  type: ClusterIP

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  auth:
    database: keycloak

resources:
  requests:
    cpu: 250m
    memory: 768Mi
  limits:
    cpu: 1000m
    memory: 1536Mi
