# Base Image Configuration
BASE_IMAGE_NAME ?= quay.io/jupyter/datascience-notebook
BASE_IMAGE_TAG ?= 2026-03-02

# Custom Image Configuration
IMAGE_REGISTRY ?= quay.io
IMAGE_NAMESPACE ?= metasync
IMAGE_NAME ?= data-engineering-notebook
IMAGE_TAG ?= $(BASE_IMAGE_TAG)

# Tool Versions
UV_VERSION ?= 0.10.8
JUPYTER_SERVER_PROXY_VERSION ?= 4.4.0
