apiService:
  create: true
  insecureSkipTLSVerify: true

args:
  - --kubelet-insecure-tls

livenessProbe:
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  timeoutSeconds: 5
  failureThreshold: 6

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
