mode: standalone
replicas: 1
drivesPerNode: 1
pools: 1

image:
  repository: ${MINIO_IMAGE_REPOSITORY}
  tag: ${MINIO_IMAGE_TAG}

mcImage:
  repository: ${MINIO_MC_IMAGE_REPOSITORY}
  tag: ${MINIO_MC_IMAGE_TAG}

existingSecret: "minio-auth"

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

buckets:
  - name: starrocks
    policy: none
    purge: false
